### ISSUE TITLE
docker image 로 시작하면 포트번호로 접근 가능한 이미지 생성

### ISSUE THREAD

**Issue by hyu-leeky** [kmu-bigdata/jupyter-notebook#1]
docker run 으로 했을때 바로 동작하는 이미지로 업데이트 필요.

**Comment by hyu-leeky** [comment]
현재는 port 번호 설정 후에도 정상적으로 접근이 안됨

**Comment by mjaysonnn** [comment]
```
sudo docker pull kmubigdata/jupyter-notebook
sudo docker run -d -p 8999:8888 -e PASSWORD="mj" kmubigdata/jupyter-notebook
```

위 2가지 command를 bd-1 , bd-2 , gpu-titan-x 에서 하고 각각 url에 접속해봤는데 다 성공했습니다.

![image](https://user-images.githubusercontent.com/14160977/38420623-5b9f2834-39df-11e8-86b8-bd7d5acd795f.png)

![image](https://user-images.githubusercontent.com/14160977/38420642-660a0eb0-39df-11e8-8d35-e079f2e6ece2.png)



혹시 한번더 확인해주실수 있으신가요?

docker run -d -p 포트번호:8888 -e PASSWORD="비밀번호" kmubigdata/jupyter-notebook

**Comment by hyu-leeky** [comment]
9999 포트 번호가 이상한지안되네.
다른 포트 번호로 하니까 된다.
잘 작업해뒀었네 ㅎㅎ 땡큐~

**Comment by mjaysonnn** [comment]
옙!
